const pilotCourses = [
  {
    id: 'CSE231',
    nameKo: 'Data Structures',
    nameEn: 'Data Structures',
    type: 'REQUIRED',
    credits: 3,
    department: 'Computer Science & Engineering',
    tags: ['Data Science', 'Algorithms'],
  },
  {
    id: 'CSE342',
    nameKo: 'Artificial Intelligence',
    nameEn: 'Artificial Intelligence',
    type: 'ELECTIVE',
    credits: 3,
    department: 'Computer Science & Engineering',
    tags: ['AI', 'Machine Learning'],
  },
  {
    id: 'MAT240',
    nameKo: 'Probability and Statistics',
    nameEn: 'Probability and Statistics',
    type: 'GEN_ED',
    credits: 3,
    department: 'Mathematics',
    tags: ['Data Science', 'Statistics'],
  },
  {
    id: 'GED120',
    nameKo: 'Digital Society and Ethics',
    nameEn: 'Digital Society and Ethics',
    type: 'GEN_ED',
    credits: 2,
    department: 'General Education',
    tags: ['AI', 'Ethics'],
  },
];

const pilotPrograms = [
  {
    id: 'PRG-AI-HACK',
    title: 'AI Agent Hackathon',
    description: 'Build useful AI agents with a student team.',
    date: '2026-08-10',
    category: 'Hackathon',
    tags: ['AI', 'Data Science', 'Programming'],
    careerTags: ['Technology', 'Research'],
    eligibleMajors: ['Computer Science & Engineering'],
    languages: ['English', 'Korean'],
    minYear: 2,
    maxYear: 4,
  },
  {
    id: 'PRG-RESEARCH-LAB',
    title: 'Undergraduate AI Research Lab',
    description: 'Join a supervised AI research project for one semester.',
    date: '2026-09-01',
    category: 'Research',
    tags: ['AI', 'Machine Learning', 'Research'],
    careerTags: ['Artificial Intelligence', 'Technology'],
    eligibleMajors: ['Computer Science & Engineering'],
    languages: ['English'],
    minYear: 3,
    maxYear: 4,
  },
];

const pilotScholarships = [
  {
    id: 'SCH-AI-TALENT',
    title: 'PNU AI Talent Scholarship',
    description: 'Support for students building strong AI and data skills.',
    amount: 'KRW 1,500,000',
    deadline: '2026-08-15',
    provider: 'PNU College of Information and Biomedical Engineering',
    eligibleMajors: ['Computer Science & Engineering'],
    eligibleNationalities: [],
    minGpa: 3.2,
    minTopikLevel: 3,
    minYear: 2,
    maxYear: 4,
    tags: ['AI', 'Data Science', 'Research'],
  },
  {
    id: 'SCH-INTL-SUPPORT',
    title: 'International Student Support Scholarship',
    description: 'General support for eligible international students.',
    amount: 'KRW 800,000',
    deadline: '2026-07-30',
    provider: 'PNU Office of International Services',
    eligibleMajors: [],
    eligibleNationalities: ['Mongolia', 'Vietnam', 'Indonesia'],
    minGpa: 3.0,
    minTopikLevel: 2,
    minYear: 1,
    maxYear: 4,
    tags: ['International', 'Student Support'],
  },
];

const pilotCareers = [
  {
    id: 'career-ai-engineer',
    title: 'AI Engineer',
    description: 'Builds intelligent systems, machine learning models, and AI-powered software products.',
    academicAreas: ['Programming', 'Data Science', 'Machine Learning'],
    activities: ['Hackathons', 'AI Projects'],
    strengths: ['Problem Solving', 'Teamwork', 'Systems Thinking'],
    careerAreas: ['Technology', 'Artificial Intelligence'],
    learningStyles: ['Project Based Learning', 'Self Directed Learning'],
    interests: ['AI', 'Data Science'],
    languages: ['English', 'Korean'],
  },
  {
    id: 'career-data-scientist',
    title: 'Data Scientist',
    description: 'Analyzes data, builds predictive models, and communicates insights for decision making.',
    academicAreas: ['Data Science', 'Statistics', 'Programming'],
    activities: ['Data Analysis Projects', 'Hackathons'],
    strengths: ['Problem Solving', 'Communication'],
    careerAreas: ['Technology', 'Analytics'],
    learningStyles: ['Project Based Learning', 'Research Based Learning'],
    interests: ['Data Science', 'AI'],
    languages: ['English'],
  },
];

const pilotNotices = [
  {
    id: 'NTC-REGISTRATION',
    title: 'Fall 2026 Course Registration',
    body: 'Prepare your course plan before registration opens.',
    category: 'REGISTRATION',
    priority: 'HIGH',
    deadline: '2026-08-10',
    targetMajors: ['Computer Science & Engineering'],
    targetNationalities: [],
    minYear: 1,
    maxYear: 4,
    tags: ['Data Science', 'Course Planning'],
    languages: ['English', 'Korean'],
  },
];

const gapTargetMajors = {
  'artificial-intelligence': {
    name: 'Artificial Intelligence',
    academicAreas: ['Programming', 'Mathematics', 'Machine Learning'],
    activities: ['Hackathons', 'Research'],
    strengths: ['Problem Solving', 'Analytical Thinking'],
    careerAreas: ['Technology', 'Artificial Intelligence'],
    learningStyles: ['Project Based Learning', 'Self Directed Learning'],
    minTopikLevel: 4,
  },
  'computer-engineering': {
    name: 'Computer Engineering',
    academicAreas: ['Programming', 'Systems', 'Hardware'],
    activities: ['Hackathons', 'Engineering Projects'],
    strengths: ['Problem Solving', 'Systems Thinking'],
    careerAreas: ['Technology', 'Engineering'],
    learningStyles: ['Project Based Learning', 'Hands On Learning'],
    minTopikLevel: 4,
  },
  'design-technology': {
    name: 'Design Technology',
    academicAreas: ['Design', 'Technology', 'User Experience'],
    activities: ['Design Projects', 'Prototyping'],
    strengths: ['Creativity', 'Communication'],
    careerAreas: ['Design', 'Technology'],
    learningStyles: ['Project Based Learning', 'Visual Learning'],
    minTopikLevel: 4,
  },
  'business-administration': {
    name: 'Business Administration',
    academicAreas: ['Business', 'Economics', 'Management'],
    activities: ['Case Studies', 'Internships'],
    strengths: ['Communication', 'Leadership'],
    careerAreas: ['Business', 'Management'],
    learningStyles: ['Discussion Based Learning', 'Case Based Learning'],
    minTopikLevel: 5,
  },
};

module.exports = {
  pilotCourses,
  pilotPrograms,
  pilotScholarships,
  pilotCareers,
  pilotNotices,
  gapTargetMajors,
};
