-- Controlled, one-time Business Administration curriculum import support.
--
-- Install this migration before running scripts/apply-business-curriculum.mjs.
-- The application RPC accepts only the exact reviewed package checksum and
-- refuses to write if the 2026-08-14 production snapshot has drifted.

begin;

alter table public.course
  add column if not exists course_name_en text null;

do $migration_guard$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'course'
      and column_name = 'course_name_en'
      and data_type = 'text'
      and is_nullable = 'YES'
  ) then
    raise exception 'course.course_name_en exists with an unexpected schema';
  end if;
end
$migration_guard$;

create table if not exists public.course_curriculum (
  course_curriculum_id bigint generated by default as identity primary key,
  course_id integer not null,
  major_id integer not null,
  curriculum_year smallint not null,
  source_course_code text not null,
  category text not null,
  recommended_year smallint not null,
  grade_semester text not null,
  source_department text null,
  source_file_sha256 text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint course_curriculum_course_id_fkey
    foreign key (course_id) references public.course(course_id) on delete cascade,
  constraint course_curriculum_major_id_fkey
    foreign key (major_id) references public.major(major_id) on delete cascade,
  constraint course_curriculum_year_check
    check (curriculum_year between 2000 and 2100),
  constraint course_curriculum_source_code_nonblank_check
    check (length(btrim(source_course_code)) > 0),
  constraint course_curriculum_category_check
    check (category in ('REQUIRED', 'ELECTIVE')),
  constraint course_curriculum_recommended_year_check
    check (recommended_year between 1 and 4),
  constraint course_curriculum_grade_semester_nonblank_check
    check (length(btrim(grade_semester)) > 0),
  constraint course_curriculum_source_sha256_check
    check (source_file_sha256 ~ '^[0-9a-f]{64}$'),
  constraint course_curriculum_major_year_code_key
    unique (major_id, curriculum_year, source_course_code)
);

create index if not exists course_curriculum_course_id_idx
  on public.course_curriculum (course_id);
create index if not exists course_curriculum_major_year_idx
  on public.course_curriculum (major_id, curriculum_year);

alter table public.course_curriculum enable row level security;

-- No anon/authenticated policies are created. Curriculum maintenance remains
-- backend-only until separately reviewed read policies are approved.

create or replace function public.preflight_reviewed_business_curriculum(
  p_package jsonb,
  p_expected_checksum text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  reviewed_checksum constant text :=
    '5ce18178c2403ebe85c35ae6515c25f8f7cc6921fab32a2118e7c1711fc76d54';
  reviewed_source_sha256 constant text :=
    '7d64e59d8baa403c9264f021a9585597fcc8bc8a93f3b290f738824b7bcd5d6d';
  dataset jsonb := p_package -> 'dataset';
begin
  if p_package is null or jsonb_typeof(dataset) <> 'object' then
    raise exception 'reviewed Business curriculum package is missing';
  end if;
  if p_expected_checksum is distinct from reviewed_checksum
    or p_package ->> 'datasetSha256' is distinct from reviewed_checksum then
    raise exception 'reviewed Business curriculum checksum mismatch';
  end if;
  if dataset ->> 'mode' is distinct from 'REVIEWED_BUSINESS_CURRICULUM_IMPORT'
    or dataset #>> '{source,sha256}' is distinct from reviewed_source_sha256 then
    raise exception 'reviewed Business curriculum source identity mismatch';
  end if;
  if (dataset #>> '{major,major_id}')::integer <> 73
    or (dataset #>> '{major,college_id}')::integer <> 4 then
    raise exception 'reviewed Business curriculum destination mismatch';
  end if;
  if jsonb_array_length(dataset -> 'sourceCourses') <> 84
    or jsonb_array_length(dataset -> 'existingCourses') <> 35
    or jsonb_array_length(dataset -> 'newCourses') <> 49
    or jsonb_array_length(dataset -> 'curriculumRows') <> 160
    or jsonb_array_length(dataset -> 'crossMajorCodeCollisions') <> 1
    or jsonb_array_length(dataset -> 'existingCodeConflicts') <> 2 then
    raise exception 'reviewed Business curriculum package count mismatch';
  end if;
  if (select count(*) from public.course) <> 1875
    or (select count(*) from public.course where major_id = 73) <> 35 then
    raise exception 'production course counts drifted since review';
  end if;
  if not exists (
    select 1 from public.major
    where major_id = 73 and major_name = 'Business Administration' and college_id = 4
  ) then
    raise exception 'Business Administration major identity drifted';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(dataset -> 'existingCourses') reviewed
    left join public.course current
      on current.course_id = (reviewed ->> 'course_id')::integer
    where current.course_id is null
      or current.course_name is distinct from reviewed ->> 'previous_course_name'
      or current.credit is distinct from (reviewed ->> 'previous_credit')::numeric
      or current.major_id is distinct from (reviewed ->> 'previous_major_id')::integer
      or current.category is distinct from reviewed ->> 'previous_category'
      or current.recommended_year is distinct from
        case when reviewed -> 'previous_recommended_year' = 'null'::jsonb
          then null else (reviewed ->> 'previous_recommended_year')::smallint end
      or current.official_course_number is distinct from
        case when reviewed -> 'previous_official_course_number' = 'null'::jsonb
          then null else reviewed ->> 'previous_official_course_number' end
  ) then
    raise exception 'one or more reviewed Business courses drifted';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(dataset -> 'newCourses') reviewed
    join public.course current
      on current.major_id = 73
      and current.course_name = reviewed ->> 'course_name_ko'
  ) then
    raise exception 'one or more planned Business courses already exist';
  end if;
  if not exists (
    select 1 from public.course
    where course_id = 5934
      and major_id = 69
      and course_name = '회계학원리'
      and official_course_number = 'DB1600358'
  ) then
    raise exception 'reviewed cross-major course-code collision drifted';
  end if;

  return jsonb_build_object(
    'ok', true,
    'datasetSha256', reviewed_checksum,
    'existingCourses', 35,
    'newCourses', 49,
    'curriculumRows', 160
  );
end
$function$;

create or replace function public.apply_reviewed_business_curriculum(
  p_package jsonb,
  p_expected_checksum text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  dataset jsonb := p_package -> 'dataset';
  updated_course_count integer;
  inserted_course_count integer;
  inserted_curriculum_count integer;
begin
  perform public.preflight_reviewed_business_curriculum(
    p_package,
    p_expected_checksum
  );

  with reviewed as (
    select value
    from jsonb_array_elements(dataset -> 'existingCourses')
  )
  update public.course current
  set
    course_name_en = reviewed.value ->> 'course_name_en',
    category = reviewed.value ->> 'category',
    recommended_year = (reviewed.value ->> 'recommended_year')::smallint,
    official_course_number = coalesce(
      current.official_course_number,
      reviewed.value ->> 'source_course_code'
    )
  from reviewed
  where current.course_id = (reviewed.value ->> 'course_id')::integer;
  get diagnostics updated_course_count = row_count;

  with reviewed as (
    select value
    from jsonb_array_elements(dataset -> 'newCourses')
  )
  insert into public.course (
    course_name,
    course_name_en,
    credit,
    major_id,
    category,
    official_course_number,
    recommended_year
  )
  select
    reviewed.value ->> 'course_name_ko',
    reviewed.value ->> 'course_name_en',
    (reviewed.value ->> 'credit')::numeric,
    73,
    reviewed.value ->> 'category',
    reviewed.value ->> 'source_course_code',
    (reviewed.value ->> 'recommended_year')::smallint
  from reviewed;
  get diagnostics inserted_course_count = row_count;

  with reviewed as (
    select value
    from jsonb_array_elements(dataset -> 'curriculumRows')
  )
  insert into public.course_curriculum (
    course_id,
    major_id,
    curriculum_year,
    source_course_code,
    category,
    recommended_year,
    grade_semester,
    source_department,
    source_file_sha256
  )
  select
    course.course_id,
    73,
    (reviewed.value ->> 'curriculum_year')::smallint,
    reviewed.value ->> 'source_course_code',
    reviewed.value ->> 'category',
    (reviewed.value ->> 'recommended_year')::smallint,
    reviewed.value ->> 'grade_semester',
    reviewed.value ->> 'source_department',
    dataset #>> '{source,sha256}'
  from reviewed
  join public.course course
    on course.major_id = 73
    and course.course_name = reviewed.value ->> 'course_name_ko'
  on conflict (major_id, curriculum_year, source_course_code) do update
  set
    course_id = excluded.course_id,
    category = excluded.category,
    recommended_year = excluded.recommended_year,
    grade_semester = excluded.grade_semester,
    source_department = excluded.source_department,
    source_file_sha256 = excluded.source_file_sha256,
    updated_at = now();
  get diagnostics inserted_curriculum_count = row_count;

  if updated_course_count <> 35
    or inserted_course_count <> 49
    or inserted_curriculum_count <> 160 then
    raise exception 'Business curriculum write count mismatch: updated %, inserted %, curriculum %',
      updated_course_count, inserted_course_count, inserted_curriculum_count;
  end if;
  if (select count(*) from public.course where major_id = 73) <> 84
    or (select count(*) from public.course_curriculum where major_id = 73) <> 160 then
    raise exception 'Business curriculum post-application count mismatch';
  end if;

  return jsonb_build_object(
    'ok', true,
    'datasetSha256', p_expected_checksum,
    'updatedCourses', updated_course_count,
    'insertedCourses', inserted_course_count,
    'curriculumRows', inserted_curriculum_count
  );
end
$function$;

revoke all on function public.preflight_reviewed_business_curriculum(jsonb, text)
  from public, anon, authenticated;
revoke all on function public.apply_reviewed_business_curriculum(jsonb, text)
  from public, anon, authenticated;
grant execute on function public.preflight_reviewed_business_curriculum(jsonb, text)
  to service_role;
grant execute on function public.apply_reviewed_business_curriculum(jsonb, text)
  to service_role;

comment on table public.course_curriculum is
  'Major- and curriculum-year-specific course classification from reviewed curriculum files.';
comment on column public.course_curriculum.grade_semester is
  'Original source value; unusual terms such as summer are preserved verbatim.';

commit;
