-- RETAINED ADDITIVE MIGRATION FOR THE REVIEWED 2026-2 SOURCE. Already applied;
-- do not rerun blindly. The definition contains no data mutation and creates
-- no client policy.

begin;

alter table public.course_offering
  add column if not exists enrollment_limit integer null,
  add column if not exists team_teaching_status text null,
  add column if not exists general_education_area text null,
  add column if not exists remarks text null;

do $migration_guard$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.course_offering'::regclass
      and conname = 'course_offering_enrollment_limit_nonnegative_check'
  ) then
    alter table public.course_offering add constraint course_offering_enrollment_limit_nonnegative_check
      check (enrollment_limit is null or enrollment_limit >= 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.course_offering'::regclass
      and conname = 'course_offering_team_teaching_status_check'
  ) then
    alter table public.course_offering add constraint course_offering_team_teaching_status_check
      check (team_teaching_status is null or team_teaching_status in ('TEAM_TAUGHT', 'NOT_TEAM_TAUGHT'));
  end if;
end
$migration_guard$;

create table if not exists public.course_offering_restriction (
  course_offering_restriction_id bigint generated by default as identity primary key,
  course_offering_id bigint not null,
  restriction_key text not null,
  source_kind text not null,
  source_rule_type text null,
  permission text null,
  department_condition text null,
  year_level_condition text null,
  domestic_foreign_condition text null,
  nationality_condition text null,
  curriculum_year_condition text null,
  completed_semesters_condition text null,
  academic_status_condition text null,
  degree_program_condition text null,
  reason text null,
  exception_text text null,
  source_file_name text null,
  constraint course_offering_restriction_offering_fkey
    foreign key (course_offering_id) references public.course_offering(course_offering_id) on delete cascade,
  constraint course_offering_restriction_key_unique unique (restriction_key),
  constraint course_offering_restriction_source_kind_check
    check (source_kind in ('RESTRICTION', 'EXCEPTION')),
  constraint course_offering_restriction_permission_check
    check (permission is null or permission in ('ALLOWED', 'PROHIBITED')),
  constraint course_offering_restriction_rule_type_check
    check (source_rule_type is null or source_rule_type in ('학과', '학년', '내외국인', '국적', '교육과정적용학년도', '이수학기')),
  constraint course_offering_restriction_kind_payload_check
    check (
      (source_kind = 'RESTRICTION' and source_rule_type is not null and permission is not null and exception_text is null)
      or (source_kind = 'EXCEPTION' and source_rule_type is null and permission is null and exception_text is not null)
    )
);

alter table public.course_offering_restriction enable row level security;

create index if not exists course_offering_restriction_offering_idx
  on public.course_offering_restriction (course_offering_id);

comment on table public.course_offering_restriction is
  'Official term/section restriction rules. NULL condition fields mean the source did not provide a structured value.';
comment on column public.course_offering_restriction.reason is
  'Official free text retained verbatim; it is not automatically classified.';

commit;
