-- ADDITIVE MIGRATION: review and apply in Supabase before adding sourced rows.
-- These tables store only externally verified course facts. Missing information
-- remains absent; application code must never infer descriptions or prerequisites.

begin;

create table if not exists public.course_source_detail (
  course_id integer primary key,
  description_ko text null,
  description_en text null,
  source_url text not null,
  syllabus_url text null,
  source_kind text not null,
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint course_source_detail_course_fkey
    foreign key (course_id) references public.course(course_id) on delete restrict,
  constraint course_source_detail_source_url_nonblank
    check (length(btrim(source_url)) > 0),
  constraint course_source_detail_source_kind_check
    check (source_kind in ('PNU_CATALOG', 'PNU_CURRICULUM', 'PNU_SYLLABUS'))
);

create table if not exists public.course_prerequisite (
  course_prerequisite_id bigint generated by default as identity primary key,
  course_id integer not null,
  prerequisite_course_id integer null,
  requirement_text text null,
  source_url text not null,
  source_kind text not null,
  created_at timestamptz not null default now(),

  constraint course_prerequisite_course_fkey
    foreign key (course_id) references public.course(course_id) on delete restrict,
  constraint course_prerequisite_required_course_fkey
    foreign key (prerequisite_course_id) references public.course(course_id) on delete restrict,
  constraint course_prerequisite_not_self
    check (prerequisite_course_id is null or prerequisite_course_id <> course_id),
  constraint course_prerequisite_source_url_nonblank
    check (length(btrim(source_url)) > 0),
  constraint course_prerequisite_source_kind_check
    check (source_kind in ('PNU_CATALOG', 'PNU_CURRICULUM', 'PNU_SYLLABUS')),
  constraint course_prerequisite_has_requirement
    check (prerequisite_course_id is not null or length(btrim(requirement_text)) > 0),
  constraint course_prerequisite_identity_key
    unique nulls not distinct (course_id, prerequisite_course_id, requirement_text, source_url)
);

create index if not exists course_prerequisite_course_idx
  on public.course_prerequisite (course_id);

alter table public.course_source_detail enable row level security;
alter table public.course_prerequisite enable row level security;

-- No anon/authenticated policies. The service-role backend owns reads/writes.

commit;
