-- RETAINED MIGRATION DEFINITION 1 OF 2. Already applied for the reviewed course
-- work; do not rerun blindly. Retained for audit and controlled recovery.
-- This migration stores official PNU subject identity separately from the
-- existing production course_id and creates term/section offering identity.
-- It contains no data backfill and no client policies.
-- Review this file first, then backend/supabase/course_metadata.sql.

begin;

alter table public.course
  add column if not exists official_course_number text null;

do $migration_guard$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'course'
      and column_name = 'official_course_number'
      and data_type = 'text'
      and is_nullable = 'YES'
  ) then
    raise exception 'course.official_course_number exists with an unexpected schema';
  end if;
end
$migration_guard$;

do $migration_guard$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.course'::regclass
      and conname = 'course_official_course_number_nonblank_check'
  ) then
    alter table public.course
      add constraint course_official_course_number_nonblank_check
      check (
        official_course_number is null
        or length(btrim(official_course_number)) > 0
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.course'::regclass
      and conname = 'course_official_course_number_nonblank_check'
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%btrim%official_course_number%'
  ) then
    raise exception 'course official-number check constraint has an unexpected definition';
  end if;
end
$migration_guard$;

-- Reviewed PNU snapshots reuse some official numbers across multiple managing
-- departments. The current course model is major-scoped, so global uniqueness
-- is not proven. Keep a lookup index only; do not guess a uniqueness rule.
create index if not exists course_official_course_number_idx
  on public.course (official_course_number)
  where official_course_number is not null;

create table if not exists public.course_offering (
  course_offering_id bigint generated by default as identity primary key,
  course_id integer not null,
  official_course_number text not null,
  academic_year smallint not null,
  semester text not null,
  section text not null,

  professor text null,
  year_level text null,
  theory_hours numeric null,
  practical_hours numeric null,
  schedule text null,
  classroom text null,
  remote_course_status text null,
  original_language_code text null,
  teaching_language text null,
  source_url text null,
  retrieved_at timestamptz null,

  constraint course_offering_course_id_fkey
    foreign key (course_id) references public.course(course_id) on delete cascade,
  constraint course_offering_official_number_nonblank_check
    check (length(btrim(official_course_number)) > 0),
  constraint course_offering_academic_year_check
    check (academic_year between 2000 and 2100),
  constraint course_offering_semester_check
    check (semester in ('1', '2', 'SUMMER', 'WINTER')),
  constraint course_offering_section_nonblank_check
    check (length(btrim(section)) > 0),
  constraint course_offering_theory_hours_nonnegative_check
    check (theory_hours is null or theory_hours >= 0),
  constraint course_offering_practical_hours_nonnegative_check
    check (practical_hours is null or practical_hours >= 0),
  constraint course_offering_remote_status_check
    check (
      remote_course_status is null
      or remote_course_status in ('REMOTE', 'NOT_REMOTE', 'MIXED', 'OTHER')
    ),
  constraint course_offering_original_language_code_check
    check (
      original_language_code is null
      or original_language_code in ('E', 'C', 'J', 'F', 'G', 'R')
    ),
  constraint course_offering_teaching_language_check
    check (
      teaching_language is null
      or teaching_language in ('KOREAN', 'ENGLISH', 'MIXED', 'OTHER')
    ),
  constraint course_offering_official_term_section_key
    unique (academic_year, semester, official_course_number, section),
  constraint course_offering_course_term_section_key
    unique (course_id, academic_year, semester, section)
);

do $migration_guard$
declare
  actual_column_count integer;
begin
  select count(*) into actual_column_count
  from information_schema.columns
  where table_schema = 'public' and table_name = 'course_offering';

  if actual_column_count <> 17 or exists (
    select 1
    from (
      values
        ('course_offering_id', 'bigint', 'NO', 'YES'),
        ('course_id', 'integer', 'NO', 'NO'),
        ('official_course_number', 'text', 'NO', 'NO'),
        ('academic_year', 'smallint', 'NO', 'NO'),
        ('semester', 'text', 'NO', 'NO'),
        ('section', 'text', 'NO', 'NO'),
        ('professor', 'text', 'YES', 'NO'),
        ('year_level', 'text', 'YES', 'NO'),
        ('theory_hours', 'numeric', 'YES', 'NO'),
        ('practical_hours', 'numeric', 'YES', 'NO'),
        ('schedule', 'text', 'YES', 'NO'),
        ('classroom', 'text', 'YES', 'NO'),
        ('remote_course_status', 'text', 'YES', 'NO'),
        ('original_language_code', 'text', 'YES', 'NO'),
        ('teaching_language', 'text', 'YES', 'NO'),
        ('source_url', 'text', 'YES', 'NO'),
        ('retrieved_at', 'timestamp with time zone', 'YES', 'NO')
    ) as expected(column_name, data_type, is_nullable, is_identity)
    left join information_schema.columns actual
      on actual.table_schema = 'public'
      and actual.table_name = 'course_offering'
      and actual.column_name = expected.column_name
      and actual.data_type = expected.data_type
      and actual.is_nullable = expected.is_nullable
      and actual.is_identity = expected.is_identity
    where actual.column_name is null
  ) then
    raise exception 'public.course_offering exists with an unexpected column schema';
  end if;

  if exists (
    select 1
    from (
      values
        ('course_offering_pkey', 'p'),
        ('course_offering_course_id_fkey', 'f'),
        ('course_offering_official_number_nonblank_check', 'c'),
        ('course_offering_academic_year_check', 'c'),
        ('course_offering_semester_check', 'c'),
        ('course_offering_section_nonblank_check', 'c'),
        ('course_offering_theory_hours_nonnegative_check', 'c'),
        ('course_offering_practical_hours_nonnegative_check', 'c'),
        ('course_offering_remote_status_check', 'c'),
        ('course_offering_original_language_code_check', 'c'),
        ('course_offering_teaching_language_check', 'c'),
        ('course_offering_official_term_section_key', 'u'),
        ('course_offering_course_term_section_key', 'u')
    ) as expected(constraint_name, constraint_type)
    left join pg_constraint actual
      on actual.conrelid = 'public.course_offering'::regclass
      and actual.conname = expected.constraint_name
      and actual.contype::text = expected.constraint_type
    where actual.oid is null
  ) then
    raise exception 'public.course_offering exists with missing or unexpected constraints';
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.course_offering'::regclass
      and conname = 'course_offering_course_id_fkey'
      and confrelid = 'public.course'::regclass
      and confdeltype = 'c'
  ) then
    raise exception 'course_offering course foreign key must cascade deletes';
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.course_offering'::regclass
      and conname = 'course_offering_official_term_section_key'
      and pg_get_constraintdef(oid) =
        'UNIQUE (academic_year, semester, official_course_number, section)'
  ) or not exists (
    select 1 from pg_constraint
    where conrelid = 'public.course_offering'::regclass
      and conname = 'course_offering_course_term_section_key'
      and pg_get_constraintdef(oid) =
        'UNIQUE (course_id, academic_year, semester, section)'
  ) then
    raise exception 'course_offering uniqueness constraints have unexpected definitions';
  end if;
end
$migration_guard$;

alter table public.course_offering enable row level security;

do $migration_guard$
begin
  if not exists (
    select 1 from pg_class
    where oid = 'public.course_offering'::regclass and relrowsecurity
  ) then
    raise exception 'RLS was not enabled on public.course_offering';
  end if;
end
$migration_guard$;

-- No anon or authenticated-client policies are defined. The table remains
-- backend-only by default until a separately reviewed policy migration exists.

create index if not exists course_offering_term_idx
  on public.course_offering (academic_year, semester);

comment on column public.course.official_course_number is
  'Nullable official PNU subject number. Never populate from workbook row IDs.';
comment on table public.course_offering is
  'Official PNU offering for one academic year, semester, subject number, and section.';
comment on column public.course_offering.remote_course_status is 'NULL means unknown.';
comment on column public.course_offering.original_language_code is 'NULL means unknown.';
comment on column public.course_offering.teaching_language is 'NULL means unknown.';

commit;
