-- DRAFT MIGRATION SEQUENCE 2 OF 2. Review and apply manually only after
-- backend/supabase/course_identity_and_offerings.sql.
-- This file is not executed by any npm script and must not be used to import
-- backend/data/engineering_courses.xlsx.
--
-- NULL means unknown for every assessment metadata field. Do not add
-- defaults of NONE (or false) because that would convert missing evidence into
-- an asserted negative value.

begin;

create table if not exists public.course_metadata (
  course_metadata_id bigint generated by default as identity primary key,
  course_offering_id bigint not null,

  presentation_requirement text null,
  group_project_requirement text null,
  assignment_requirement text null,
  exam_information text null,
  practical_type text null,

  source_url text null,
  source_updated_at timestamptz null,
  verified_at timestamptz null,

  constraint course_metadata_course_offering_id_fkey
    foreign key (course_offering_id)
    references public.course_offering(course_offering_id) on delete cascade,
  constraint course_metadata_presentation_requirement_check
    check (
      presentation_requirement is null
      or presentation_requirement in ('REQUIRED', 'OPTIONAL', 'NONE')
    ),
  constraint course_metadata_group_project_requirement_check
    check (
      group_project_requirement is null
      or group_project_requirement in ('REQUIRED', 'OPTIONAL', 'NONE')
    ),
  constraint course_metadata_assignment_requirement_check
    check (
      assignment_requirement is null
      or assignment_requirement in ('REQUIRED', 'OPTIONAL', 'NONE')
    ),
  constraint course_metadata_practical_type_check
    check (
      practical_type is null
      or practical_type in ('LAB', 'PRACTICAL', 'BOTH', 'NONE')
    ),
  constraint course_metadata_offering_key unique (course_offering_id)
);

do $migration_guard$
declare
  actual_column_count integer;
begin
  select count(*) into actual_column_count
  from information_schema.columns
  where table_schema = 'public' and table_name = 'course_metadata';

  if actual_column_count <> 10 or exists (
    select 1
    from (
      values
        ('course_metadata_id', 'bigint', 'NO', 'YES'),
        ('course_offering_id', 'bigint', 'NO', 'NO'),
        ('presentation_requirement', 'text', 'YES', 'NO'),
        ('group_project_requirement', 'text', 'YES', 'NO'),
        ('assignment_requirement', 'text', 'YES', 'NO'),
        ('exam_information', 'text', 'YES', 'NO'),
        ('practical_type', 'text', 'YES', 'NO'),
        ('source_url', 'text', 'YES', 'NO'),
        ('source_updated_at', 'timestamp with time zone', 'YES', 'NO'),
        ('verified_at', 'timestamp with time zone', 'YES', 'NO')
    ) as expected(column_name, data_type, is_nullable, is_identity)
    left join information_schema.columns actual
      on actual.table_schema = 'public'
      and actual.table_name = 'course_metadata'
      and actual.column_name = expected.column_name
      and actual.data_type = expected.data_type
      and actual.is_nullable = expected.is_nullable
      and actual.is_identity = expected.is_identity
    where actual.column_name is null
  ) then
    raise exception 'public.course_metadata exists with an unexpected column schema';
  end if;

  if exists (
    select 1
    from (
      values
        ('course_metadata_pkey', 'p'),
        ('course_metadata_course_offering_id_fkey', 'f'),
        ('course_metadata_presentation_requirement_check', 'c'),
        ('course_metadata_group_project_requirement_check', 'c'),
        ('course_metadata_assignment_requirement_check', 'c'),
        ('course_metadata_practical_type_check', 'c'),
        ('course_metadata_offering_key', 'u')
    ) as expected(constraint_name, constraint_type)
    left join pg_constraint actual
      on actual.conrelid = 'public.course_metadata'::regclass
      and actual.conname = expected.constraint_name
      and actual.contype::text = expected.constraint_type
    where actual.oid is null
  ) then
    raise exception 'public.course_metadata exists with missing or unexpected constraints';
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.course_metadata'::regclass
      and conname = 'course_metadata_course_offering_id_fkey'
      and confrelid = 'public.course_offering'::regclass
      and confdeltype = 'c'
  ) then
    raise exception 'course_metadata offering foreign key must cascade deletes';
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.course_metadata'::regclass
      and conname = 'course_metadata_offering_key'
      and pg_get_constraintdef(oid) = 'UNIQUE (course_offering_id)'
  ) then
    raise exception 'course_metadata offering uniqueness has an unexpected definition';
  end if;
end
$migration_guard$;

alter table public.course_metadata enable row level security;

do $migration_guard$
begin
  if not exists (
    select 1 from pg_class
    where oid = 'public.course_metadata'::regclass and relrowsecurity
  ) then
    raise exception 'RLS was not enabled on public.course_metadata';
  end if;
end
$migration_guard$;

-- No anon or authenticated-client policies are defined. The table remains
-- backend-only by default until a separately reviewed policy migration exists.

comment on table public.course_metadata is
  'Term- and section-aware course metadata backed by an authoritative syllabus source.';
comment on column public.course_metadata.presentation_requirement is 'NULL means unknown.';
comment on column public.course_metadata.group_project_requirement is 'NULL means unknown.';
comment on column public.course_metadata.assignment_requirement is 'NULL means unknown.';
comment on column public.course_metadata.exam_information is 'NULL means unknown.';
comment on column public.course_metadata.practical_type is 'NULL means unknown.';

commit;
