-- PROPOSED MIGRATION: not installed by application code.
-- Personal timetable planning is intentionally separate from enrollment.
-- Review and install in Supabase before enabling timetable writes.

begin;

create table if not exists public.student_timetable_entry (
  timetable_entry_id bigint generated by default as identity primary key,
  student_id integer not null,
  course_id integer not null,
  course_offering_id bigint null,
  academic_year smallint not null,
  semester text not null,
  source text not null,
  color text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint student_timetable_entry_student_id_fkey
    foreign key (student_id) references public.student(student_id) on delete cascade,
  constraint student_timetable_entry_course_id_fkey
    foreign key (course_id) references public.course(course_id) on delete restrict,
  constraint student_timetable_entry_offering_id_fkey
    foreign key (course_offering_id)
    references public.course_offering(course_offering_id) on delete set null,
  constraint student_timetable_entry_year_check
    check (academic_year between 2000 and 2100),
  constraint student_timetable_entry_semester_check
    check (semester in ('1', '2', 'SUMMER', 'WINTER')),
  constraint student_timetable_entry_source_check
    check (source in ('OFFERING', 'MANUAL')),
  constraint student_timetable_entry_color_check
    check (color is null or color ~ '^#[0-9A-Fa-f]{6}$'),
  constraint student_timetable_entry_student_term_course_key
    unique (student_id, academic_year, semester, course_id)
);

create table if not exists public.student_timetable_slot (
  timetable_slot_id bigint generated by default as identity primary key,
  timetable_entry_id bigint not null,
  day_of_week smallint not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  classroom text null,

  constraint student_timetable_slot_entry_id_fkey
    foreign key (timetable_entry_id)
    references public.student_timetable_entry(timetable_entry_id) on delete cascade,
  constraint student_timetable_slot_day_check
    check (day_of_week between 1 and 7),
  constraint student_timetable_slot_time_check
    check (start_time < end_time),
  constraint student_timetable_slot_entry_time_key
    unique (timetable_entry_id, day_of_week, start_time, end_time)
);

create index if not exists student_timetable_entry_student_term_idx
  on public.student_timetable_entry (student_id, academic_year, semester);
create index if not exists student_timetable_slot_entry_idx
  on public.student_timetable_slot (timetable_entry_id);

alter table public.student_timetable_entry enable row level security;
alter table public.student_timetable_slot enable row level security;

-- No client policies are defined. The Express backend validates token ownership
-- and uses its service-role connection for all timetable operations.

create or replace function public.add_student_timetable_entry(
  p_student_id integer,
  p_course_id integer,
  p_course_offering_id bigint,
  p_academic_year smallint,
  p_semester text,
  p_source text,
  p_color text,
  p_slots jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  new_entry_id bigint;
  slot_count integer;
begin
  if not exists (select 1 from public.student where student_id = p_student_id) then
    raise exception 'student not found';
  end if;
  if not exists (select 1 from public.course where course_id = p_course_id) then
    raise exception 'course not found';
  end if;
  if p_academic_year not between 2000 and 2100
    or p_semester not in ('1', '2', 'SUMMER', 'WINTER')
    or p_source not in ('OFFERING', 'MANUAL') then
    raise exception 'invalid timetable term or source';
  end if;
  if p_color is not null and p_color !~ '^#[0-9A-Fa-f]{6}$' then
    raise exception 'invalid timetable color';
  end if;
  if jsonb_typeof(p_slots) <> 'array' or jsonb_array_length(p_slots) = 0 then
    raise exception 'at least one timetable slot is required';
  end if;
  if p_course_offering_id is not null and not exists (
    select 1
    from public.course_offering offering
    where offering.course_offering_id = p_course_offering_id
      and offering.course_id = p_course_id
      and offering.academic_year = p_academic_year
      and offering.semester = p_semester
  ) then
    raise exception 'course offering does not match course and term';
  end if;

  create temporary table requested_timetable_slot (
    day_of_week smallint not null,
    start_time time without time zone not null,
    end_time time without time zone not null,
    classroom text null,
    unique (day_of_week, start_time, end_time),
    check (day_of_week between 1 and 7),
    check (start_time < end_time)
  ) on commit drop;

  insert into requested_timetable_slot (day_of_week, start_time, end_time, classroom)
  select
    (slot ->> 'day')::smallint,
    (slot ->> 'start')::time,
    (slot ->> 'end')::time,
    nullif(btrim(slot ->> 'classroom'), '')
  from jsonb_array_elements(p_slots) slot;

  select count(*) into slot_count from requested_timetable_slot;
  if slot_count <> jsonb_array_length(p_slots) then
    raise exception 'duplicate or invalid timetable slots';
  end if;

  if exists (
    select 1
    from requested_timetable_slot requested
    join public.student_timetable_entry existing_entry
      on existing_entry.student_id = p_student_id
      and existing_entry.academic_year = p_academic_year
      and existing_entry.semester = p_semester
    join public.student_timetable_slot existing_slot
      on existing_slot.timetable_entry_id = existing_entry.timetable_entry_id
      and existing_slot.day_of_week = requested.day_of_week
      and requested.start_time < existing_slot.end_time
      and existing_slot.start_time < requested.end_time
  ) then
    raise exception 'timetable conflict with an existing course';
  end if;

  insert into public.student_timetable_entry (
    student_id,
    course_id,
    course_offering_id,
    academic_year,
    semester,
    source,
    color
  ) values (
    p_student_id,
    p_course_id,
    p_course_offering_id,
    p_academic_year,
    p_semester,
    p_source,
    p_color
  )
  returning timetable_entry_id into new_entry_id;

  insert into public.student_timetable_slot (
    timetable_entry_id,
    day_of_week,
    start_time,
    end_time,
    classroom
  )
  select new_entry_id, day_of_week, start_time, end_time, classroom
  from requested_timetable_slot;

  return jsonb_build_object('timetableEntryId', new_entry_id);
exception
  when unique_violation then
    raise exception 'course already exists in this timetable';
end
$function$;

revoke all on function public.add_student_timetable_entry(
  integer, integer, bigint, smallint, text, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.add_student_timetable_entry(
  integer, integer, bigint, smallint, text, text, text, jsonb
) to service_role;

comment on table public.student_timetable_entry is
  'Personal timetable plans; entries do not assert official PNU enrollment.';
comment on table public.student_timetable_slot is
  'Normalized weekly meeting slots for personal timetable entries.';

commit;
